/**
 * UI Forge Tailwind CSS v4 Preset
 * Integrates design tokens with Tailwind's utility classes
 */

export default {
  theme: {
    extend: {
      colors: {
        primary: {
          50: 'rgb(var(--uif-primary-50) / <alpha-value>)',
          100: 'rgb(var(--uif-primary-100) / <alpha-value>)',
          200: 'rgb(var(--uif-primary-200) / <alpha-value>)',
          300: 'rgb(var(--uif-primary-300) / <alpha-value>)',
          400: 'rgb(var(--uif-primary-400) / <alpha-value>)',
          500: 'rgb(var(--uif-primary-500) / <alpha-value>)',
          600: 'rgb(var(--uif-primary-600) / <alpha-value>)',
          700: 'rgb(var(--uif-primary-700) / <alpha-value>)',
          800: 'rgb(var(--uif-primary-800) / <alpha-value>)',
          900: 'rgb(var(--uif-primary-900) / <alpha-value>)',
          950: 'rgb(var(--uif-primary-950) / <alpha-value>)',
        },
        secondary: {
          50: 'rgb(var(--uif-secondary-50) / <alpha-value>)',
          100: 'rgb(var(--uif-secondary-100) / <alpha-value>)',
          200: 'rgb(var(--uif-secondary-200) / <alpha-value>)',
          300: 'rgb(var(--uif-secondary-300) / <alpha-value>)',
          400: 'rgb(var(--uif-secondary-400) / <alpha-value>)',
          500: 'rgb(var(--uif-secondary-500) / <alpha-value>)',
          600: 'rgb(var(--uif-secondary-600) / <alpha-value>)',
          700: 'rgb(var(--uif-secondary-700) / <alpha-value>)',
          800: 'rgb(var(--uif-secondary-800) / <alpha-value>)',
          900: 'rgb(var(--uif-secondary-900) / <alpha-value>)',
          950: 'rgb(var(--uif-secondary-950) / <alpha-value>)',
        },
        success: {
          50: 'rgb(var(--uif-success-50) / <alpha-value>)',
          100: 'rgb(var(--uif-success-100) / <alpha-value>)',
          200: 'rgb(var(--uif-success-200) / <alpha-value>)',
          300: 'rgb(var(--uif-success-300) / <alpha-value>)',
          400: 'rgb(var(--uif-success-400) / <alpha-value>)',
          500: 'rgb(var(--uif-success-500) / <alpha-value>)',
          600: 'rgb(var(--uif-success-600) / <alpha-value>)',
          700: 'rgb(var(--uif-success-700) / <alpha-value>)',
          800: 'rgb(var(--uif-success-800) / <alpha-value>)',
          900: 'rgb(var(--uif-success-900) / <alpha-value>)',
          950: 'rgb(var(--uif-success-950) / <alpha-value>)',
        },
        warning: {
          50: 'rgb(var(--uif-warning-50) / <alpha-value>)',
          100: 'rgb(var(--uif-warning-100) / <alpha-value>)',
          200: 'rgb(var(--uif-warning-200) / <alpha-value>)',
          300: 'rgb(var(--uif-warning-300) / <alpha-value>)',
          400: 'rgb(var(--uif-warning-400) / <alpha-value>)',
          500: 'rgb(var(--uif-warning-500) / <alpha-value>)',
          600: 'rgb(var(--uif-warning-600) / <alpha-value>)',
          700: 'rgb(var(--uif-warning-700) / <alpha-value>)',
          800: 'rgb(var(--uif-warning-800) / <alpha-value>)',
          900: 'rgb(var(--uif-warning-900) / <alpha-value>)',
          950: 'rgb(var(--uif-warning-950) / <alpha-value>)',
        },
        danger: {
          50: 'rgb(var(--uif-danger-50) / <alpha-value>)',
          100: 'rgb(var(--uif-danger-100) / <alpha-value>)',
          200: 'rgb(var(--uif-danger-200) / <alpha-value>)',
          300: 'rgb(var(--uif-danger-300) / <alpha-value>)',
          400: 'rgb(var(--uif-danger-400) / <alpha-value>)',
          500: 'rgb(var(--uif-danger-500) / <alpha-value>)',
          600: 'rgb(var(--uif-danger-600) / <alpha-value>)',
          700: 'rgb(var(--uif-danger-700) / <alpha-value>)',
          800: 'rgb(var(--uif-danger-800) / <alpha-value>)',
          900: 'rgb(var(--uif-danger-900) / <alpha-value>)',
          950: 'rgb(var(--uif-danger-950) / <alpha-value>)',
        },
        neutral: {
          50: 'rgb(var(--uif-neutral-50) / <alpha-value>)',
          100: 'rgb(var(--uif-neutral-100) / <alpha-value>)',
          200: 'rgb(var(--uif-neutral-200) / <alpha-value>)',
          300: 'rgb(var(--uif-neutral-300) / <alpha-value>)',
          400: 'rgb(var(--uif-neutral-400) / <alpha-value>)',
          500: 'rgb(var(--uif-neutral-500) / <alpha-value>)',
          600: 'rgb(var(--uif-neutral-600) / <alpha-value>)',
          700: 'rgb(var(--uif-neutral-700) / <alpha-value>)',
          800: 'rgb(var(--uif-neutral-800) / <alpha-value>)',
          900: 'rgb(var(--uif-neutral-900) / <alpha-value>)',
          950: 'rgb(var(--uif-neutral-950) / <alpha-value>)',
        },
        background: 'rgb(var(--uif-background) / <alpha-value>)',
        foreground: 'rgb(var(--uif-foreground) / <alpha-value>)',
        card: {
          DEFAULT: 'rgb(var(--uif-card) / <alpha-value>)',
          foreground: 'rgb(var(--uif-card-foreground) / <alpha-value>)',
        },
        popover: {
          DEFAULT: 'rgb(var(--uif-popover) / <alpha-value>)',
          foreground: 'rgb(var(--uif-popover-foreground) / <alpha-value>)',
        },
        muted: {
          DEFAULT: 'rgb(var(--uif-muted) / <alpha-value>)',
          foreground: 'rgb(var(--uif-muted-foreground) / <alpha-value>)',
        },
        accent: {
          DEFAULT: 'rgb(var(--uif-accent) / <alpha-value>)',
          foreground: 'rgb(var(--uif-accent-foreground) / <alpha-value>)',
        },
        border: 'rgb(var(--uif-border) / <alpha-value>)',
        input: 'rgb(var(--uif-input) / <alpha-value>)',
        ring: 'rgb(var(--uif-ring) / <alpha-value>)',
      },
      fontFamily: {
        sans: 'var(--uif-font-sans)',
        mono: 'var(--uif-font-mono)',
      },
      borderRadius: {
        none: 'var(--uif-radius-none)',
        sm: 'var(--uif-radius-sm)',
        base: 'var(--uif-radius-base)',
        md: 'var(--uif-radius-md)',
        lg: 'var(--uif-radius-lg)',
        xl: 'var(--uif-radius-xl)',
        '2xl': 'var(--uif-radius-2xl)',
        full: 'var(--uif-radius-full)',
      },
      boxShadow: {
        sm: 'var(--uif-shadow-sm)',
        DEFAULT: 'var(--uif-shadow-base)',
        md: 'var(--uif-shadow-md)',
        lg: 'var(--uif-shadow-lg)',
        xl: 'var(--uif-shadow-xl)',
        '2xl': 'var(--uif-shadow-2xl)',
      },
      transitionDuration: {
        fast: 'var(--uif-transition-fast)',
        base: 'var(--uif-transition-base)',
        slow: 'var(--uif-transition-slow)',
      },
      zIndex: {
        dropdown: 'var(--uif-z-dropdown)',
        sticky: 'var(--uif-z-sticky)',
        fixed: 'var(--uif-z-fixed)',
        'modal-backdrop': 'var(--uif-z-modal-backdrop)',
        modal: 'var(--uif-z-modal)',
        popover: 'var(--uif-z-popover)',
        tooltip: 'var(--uif-z-tooltip)',
      },
    },
  },
};
